COUNTRY_MAPPINGS = {
	'Malaysia':['Johor',
                'Kedah',
                'Kelantan',
                'Malacca',
                'Negeri Sembilan',
                'Pahang',
                'Penang',
                'Perak',
                'Perlis',
                'Sabah',
                'Sarawak',
                'Selangor',
                'Terengganu',
                'Kuala Lumpur',
                'Putrajaya',
                'Labuan'],
	'Vietnam':['Bắc Giang',
                'Bắc Kạn',
                'Cao Bằng',
                'Hà Giang',
                'Lạng Sơn',
                'Phú Thọ',
                'Quảng Ninh',
                'Thái Nguyên',
                'Tuyên Quang',
                'Lào Cai',
                'Yên Bái',
                'Điện Biên',
                'Hòa Bình',
                'Lai Châu',
                'Sơn La',
                'Bắc Ninh',
                'Hà Nam',
                'Hải Dương',
                'Hưng Yên',
                'Nam Định',
                'Ninh Bình',
                'Thái Bình',
                'Vĩnh Phúc',
                'Hà Nội',
                'Hải Phòng',
                'Hà Tĩnh',
                'Nghệ An',
                'Quảng Bình',
                'Quảng Trị',
                'Thanh Hóa',
                'Thừa Thiên-Huế',
                'Đắk Lắk',
                'Đắk Nông',
                'Gia Lai',
                'Kon Tum',
                'Lâm Đồng',
                'Bình Định',
                'Bình Thuận',
                'Khánh Hòa',
                'Ninh Thuận',
                'Phú Yên',
                'Quảng Nam',
                'Quảng Ngãi',
                'Đà Nẵng',
                'Bà Rịa-Vũng Tàu',
                'Bình Dương',
                'Bình Phước',
                'Đồng Nai',
                'Tây Ninh',
                'Hồ Chí Minh',
                'An Giang',
                'Bạc Liêu',
                'Bến Tre',
                'Cà Mau',
                'Đồng Tháp',
                'Hậu Giang',
                'Kiên Giang',
                'Long An',
                'Sóc Trăng',
                'Tiền Giang',
                'Trà Vinh',
                'Vĩnh Long',
                'Cần Thơ'],
	'Singapore':['Bishan',
                'Bukit Merah',
                'Bukit Timah',
                'Downtown Core',
                'Geylang',
                'Kallang',
                'Marina East',
                'Marina South',
                'Marine Parade',
                'Newton',
                'Novena',
                'Orchard',
                'Outram',
                'Queenstown',
                'River Valley',
                'Rochor',
                'Singapore River',
                'Southern Islands',
                'Straits View',
                'Tanglin',
                'Toa Payoh'],
	'Thailand':['Bangkok',
                'Amnat Charoen',
                'Ang Thong',
                'Bueng Kan',
                'Buriram',
                'Chachoengsao',
                'Chai Nat',
                'Chaiyaphum',
                'Chanthaburi',
                'Chiang Mai',
                'Chiang Rai',
                'Chonburi',
                'Chumphon',
                'Kalasin',
                'Kamphaeng Phet',
                'Kanchanaburi',
                'Khon Kaen',
                'Krabi',
                'Lampang',
                'Lamphun',
                'Loei',
                'Lopburi',
                'Mae Hong Son',
                'Maha Sarakham',
                'Mukdahan',
                'Nakhon Nayok',
                'Nakhon Pathom',
                'Nakhon Phanom',
                'Nakhon Ratchasima',
                'Nakhon Sawan',
                'Nakhon Si Thammarat',
                'Nan',
                'Narathiwat',
                'Nong Bua Lamphu',
                'Nong Khai',
                'Nonthaburi',
                'Pathum Thani',
                'Pattani',
                'Phang Nga',
                'Phatthalung',
                'Phayao',
                'Phetchabun',
                'Phetchaburi',
                'Phichit',
                'Phitsanulok',
                'Phra Nakhon Si Ayutthaya',
                'Phrae',
                'Phuket',
                'Prachinburi',
                'Prachuap Khiri Khan',
                'Ranong',
                'Ratchaburi',
                'Rayong',
                'Roi Et',
                'Sa Kaeo',
                'Sakon Nakhon',
                'Samut Prakan',
                'Samut Sakhon',
                'Samut Songkhram',
                'Saraburi',
                'Satun',
                'Sing Buri',
                'Sisaket',
                'Songkhla',
                'Sukhothai',
                'Suphan Buri',
                'Surat Thani',
                'Surin',
                'Tak',
                'Trang',
                'Trat',
                'Ubon Ratchathani',
                'Udon Thani',
                'Uthai Thani',
                'Uttaradit',
                'Yala',
                'Yasothon'],
	'Indonesia':['Aceh',
                'Bali',
                'Bangka Belitung Islands',
                'Banten',
                'Bengkulu',
                'Central Java',
                'Central Kalimantan',
                'Central Sulawesi',
                'East Java',
                'East Kalimantan[6]',
                'East Nusa Tenggara',
                'Gorontalo',
                'Special Capital Region of Jakarta',
                'Jambi',
                'Lampung',
                'Maluku',
                'North Kalimantan',
                'North Maluku',
                'North Sulawesi',
                'North Sumatra',
                'Papua',
                'Riau',
                'Riau Islands',
                'Southeast Sulawesi',
                'South Kalimantan',
                'South Sulawesi',
                'South Sumatra',
                'West Java',
                'West Kalimantan',
                'West Nusa Tenggara',
                'West Papua',
                'West Sulawesi',
                'West Sumatra',
                'Special Region of Yogyakarta'],
	'Philippines':['Abra',
                    'Agusan del Norte',
                    'Agusan del Sur',
                    'Aklan',
                    'Albay',
                    'Antique',
                    'Apayao',
                    'Aurora',
                    'Basilan',
                    'Bataan',
                    'Batanes',
                    'Batangas',
                    'Benguet',
                    'Biliran',
                    'Bohol',
                    'Bukidnon',
                    'Bulacan',
                    'Cagayan',
                    'Camarines Norte',
                    'Camarines Sur',
                    'Camiguin',
                    'Capiz',
                    'Catanduanes',
                    'Cavite',
                    'Cebu[viii]',
                    'Cotabato',
                    'Davao de Oro',
                    'Davao del Norte',
                    'Davao del Sur',
                    'Davao Occidental',
                    'Davao Oriental',
                    'Dinagat Islands',
                    'Eastern Samar',
                    'Guimaras',
                    'Ifugao',
                    'Ilocos Norte',
                    'Ilocos Sur',
                    'Iloilo',
                    'Isabela',
                    'Kalinga',
                    'La Union',
                    'Laguna',
                    'Lanao del Norte',
                    'Lanao del Sur',
                    'Leyte',
                    'Maguindanao',
                    'Marinduque',
                    'Masbate',
                    'Misamis Occidental',
                    'Misamis Oriental',
                    'Mountain Province',
                    'Negros Occidental',
                    'Negros Oriental',
                    'Northern Samar',
                    'Nueva Ecija',
                    'Nueva Vizcaya',
                    'Occidental Mindoro',
                    'Oriental Mindoro',
                    'Palawan',
                    'Pampanga',
                    'Pangasinan',
                    'Quezon',
                    'Quirino',
                    'Rizal',
                    'Romblon',
                    'Samar',
                    'Sarangani',
                    'Siquijor',
                    'Sorsogon',
                    'South Cotabato',
                    'Southern Leyte',
                    'Sultan Kudarat',
                    'Sulu',
                    'Surigao del Norte',
                    'Surigao del Sur',
                    'Tarlac',
                    'Tawi-Tawi',
                    'Zambales',
                    'Zamboanga del Norte',
                    'Zamboanga del Sur',
                    'Zamboanga Sibugay',
                    'Metro Manila'],
	'Brunei':['Brunei'],
	'Cambodia':['Banteay Meanchey',
                'Battambang',
                'Kampong Cham',
                'Kampong Chhnang',
                'Kampong Speu',
                'Kampong Thom',
                'Kampot',
                'Kandal',
                'Koh Kong',
                'Kratié',
                'Mondulkiri',
                'Phnom Penh',
                'Preah Vihear',
                'Prey Veng',
                'Pursat',
                'Ratanak Kiri',
                'Siem Reap',
                'Preah Sihanouk',
                'Stung Treng',
                'Svay Rieng',
                'Takéo',
                'Oddar Meanchey',
                'Kep',
                'Pailin',
                'Tboung Khmum'],
	'Myanmar':['Thaninthayi',
                'Mon',
                'Yangon',
                'Ayeyarwaddy',
                'Kayin',
                'Bago',
                'Rakhine',
                'Magwe',
                'Mandalay',
                'Kayah',
                'Shan',
                'Sagaing',
                'Chin',
                'Kachin']
    }